services:
  - type: web
    name: log-web
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=460
      - key: HOSTNAME
        value: 0.0.0.0
      - key: NEXT_PUBLIC_API_URL
        sync: false
